### ISSUE TITLE
[BUG] It is not possible to open generated osm.pbf in JOSM editor

### ISSUE THREAD

**Issue by zdila** [navigatorsguild/osm-io#24]
**Describe the bug**

It is not possible to open generated osm.pbf in JOSM editor. Osmium can process it.

JOSM error message for `CompressionType::Zlib`: `Could not read file 'out.osm.pbf'. Error is: java.io.EOFException: Unexpected end of ZLIB input stream`

JOSM error message for `CompressionType::Uncompressed`: `No data fount in file unc.osm.pbf`, but after converting with osmium I see nodes/ways/relations.

**Package version**
- 0.1.1

**To Reproduce**

Write osm.pbf file and open it in JOSM

**Expected behavior**

It should be possible to open the file on JOSM

**Comment by giora-kosoi-ng** [comment]
Thanks a lot for reporting the bug. Will review and update until the end of the week.

**Comment by zdila** [comment]
My new observations:

- if I use `CompressionType::Zlib` then `osmium fileinfo output.osm.pbf` says `Compression: none`
- if I use `osmium cat output.osm.pbf -o fixed.osm.bpf` then JOSM can open `fixed.osm.bpf`, but it fails on Integer overflow if I copy feature timestamps from input pbf like this:

```rust
Node::new(
    node.id(),
    node.version(),
    node.coordinate().clone(),
    node.timestamp(), // <-- I must set valid timestamp here, eg. `SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs() as i64`
    node.changeset(),
    node.uid(),
    node.user().to_owned(),
    node.visible(),
    Vec::with_capacity(0),
)
```

This produces random timestamps (some in far future and some in far past).

Source code JOSM is using for reading osm.pbf: https://github.com/JOSM/josm/blob/master/src/org/openstreetmap/josm/io/OsmPbfReader.java

**Comment by giora-kosoi-ng** [comment]
Thanks a lot @zdila for submitting additional info, I started to work on the JOSM issue, which is actually several issues caused by the hand written protobuf implementation. 
The first issue that I found and have a fix for it is that JOSM relies on the order in which the Blob message is serialized, however there are more issues that will take me some time to debug and submit a fix to JOSM.

**Comment by giora-kosoi-ng** [comment]
Submitted a [patch](https://josm.openstreetmap.de/ticket/23550) to JOSM. The patch was tested with Niue and Malta files generated by osm-io and by files downloaded from https://download.geofabrik.de/

Fixed in osm-io v0.1.3

**Comment by zdila** [comment]
Awesome. Thank you!

**Comment by zdila** [comment]
Tested with your JOSM patch and it indeed woks!
